set runtimepath+=$HOME/.vim/
runtime! rc/*.vim


autocmd BufNewFile,BufRead *.tsx let b:tsx_ext_found = 1
autocmd BufNewFile,BufRead *.tsx set filetype=typescript.tsx
autocmd BufNewFile,BufRead *.styl set filetype=stylus
