[[plugins]]  # プラグインマネージャ
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'raphamorim/lucario'

[[plugins]]  # Vimプロセス非同期実行ライブラリ
repo = 'Shougo/vimproc.vim'

[[plugins]]  # カーソル位置のファイルタイプを特定する
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]  # toml syntax support
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]  # language server
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
build = './install.sh nightly'
hook_add = '''
  let g:coc_global_extensions = [
    \  'coc-xml'
    \, 'coc-html'
    \, 'coc-markdownlint'
    \, 'coc-css'
    \, 'coc-json'
    \, 'coc-prisma'
    \, 'coc-dlang'
    \, 'coc-java'
    \, 'coc-kotlin'
    \, 'coc-tsserver'
    \, 'coc-eslint'
    \, 'coc-prettier'
    \, '@yaegassy/coc-volar'
    \, 'coc-deno'
    \, 'coc-pyright'
    \ ]
  set signcolumn=yes
  highlight! link SignColumn LineNr
  highlight CocFloating ctermfg=255 ctermbg=242
  highlight CocWarningFloat ctermfg=255
  highlight CocErrorFloat ctermfg=255

  inoremap <silent> <expr> <TAB>
      \ coc#pum#visible()
      \ ? coc#pum#next(1)
      \ : "\<Tab>"
  inoremap <expr> <S-TAB>
      \ coc#pum#visible()
      \ ? coc#pum#prev(1)
      \ : "\<C-h>"
  inoremap <silent> <expr> <CR>
      \ coc#pum#visible()
      \ ? coc#pum#confirm()
      \ : "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

  command! -nargs=0 Prettier :CocCommand prettier.formatFile
  autocmd FileType vue call coc#config('volar.takeOverMode.enabled', v:true)
  autocmd FileType vue call coc#config('tsserver.enable', v:false)
'''

[[plugins]]  # previm実行時にブラウザを起動する
repo = 'tyru/open-browser.vim'

[[plugins]]  # Markdown, PlantUML等のプレビュー
repo = 'previm/previm'
