[[plugins]]  # プラグインマネージャ
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'raphamorim/lucario'

[[plugins]]  # Vimプロセス非同期実行ライブラリ
repo = 'Shougo/vimproc.vim'

[[plugins]]  # カーソル位置のファイルタイプを特定する
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]  # toml syntax support
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]  # language server
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
build = './install.sh nightly'
hook_add = '''
  inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
  inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
  let g:coc_global_extensions = [
    \  'coc-xml'
    \, 'coc-html'
    \, 'coc-css'
    \, 'coc-markdownlint'
    \, 'coc-json'
    \, 'coc-tsserver'
    \, 'coc-eslint'
    \, 'coc-prettier'
    \, 'coc-deno'
    \, 'coc-java'
    \, 'coc-kotlin'
    \ ]
  command! -nargs=0 Prettier :CocCommand prettier.formatFile
'''

[[plugins]]  # Markdown, PlantUML等のプレビュー
repo = 'previm/previm'
hook_add = '''
  command! -nargs=0 Preview :PrevimOpen
'''

[[plugins]]  # previm実行時にブラウザを起動する
repo = 'tyru/open-browser.vim'
