[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'raphamorim/lucario'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
build = './install.sh nightly'
hook_add = '''
  inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
  inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
'''

[[plugins]]
repo = 'kazuph/previm'
rev = 'feature/add-plantuml-plugin'
hook_add = '''
  nnoremap <silent><Space><Space>p :PrevimOpen<CR>
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
hook_add = '''
  let g:table_mode_corner = '|'
'''
